//go:build ignore

/*
   Copyright Mycophonic.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

// Command gen_unicode9 writes unicode9.go, the code points assigned in Unicode
// 9.0, from Unicode's DerivedAge.txt for that version, kept in testdata/ucd as
// published at https://www.unicode.org/Public/9.0.0/ucd/DerivedAge.txt
// (SHA-256 5cb15b04693c43df16e0d304deca049e93b001445d163184e0ff1b7c8c852146),
// less one trailing space on a comment line, which the commit lint refuses.
// DerivedAge dates the noncharacters too; they are not assigned (general
// category Cn), and the file labels them, so they are left out. Run it with
// `go generate` in this directory.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strconv"
	"strings"
	"unicode"
)

type span struct{ lo, hi uint32 }

func main() {
	source, err := os.Open("testdata/ucd/DerivedAge-9.0.0.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer source.Close()

	var spans []span

	scanner := bufio.NewScanner(source)
	for scanner.Scan() {
		line, comment, _ := strings.Cut(scanner.Text(), "#")
		if strings.Contains(comment, "<noncharacter-") {
			continue
		}

		points, _, found := strings.Cut(line, ";")
		if !found {
			continue
		}

		low, high, isRange := strings.Cut(strings.TrimSpace(points), "..")
		if !isRange {
			high = low
		}

		lo, err := strconv.ParseUint(low, 16, 32)
		if err != nil {
			log.Fatal(err)
		}

		hi, err := strconv.ParseUint(high, 16, 32)
		if err != nil {
			log.Fatal(err)
		}

		spans = append(spans, span{uint32(lo), uint32(hi)})
	}

	if err = scanner.Err(); err != nil {
		log.Fatal(err)
	}

	slices.SortFunc(spans, func(a, b span) int { return int(a.lo) - int(b.lo) })

	merged := spans[:1]
	for _, s := range spans[1:] {
		if last := &merged[len(merged)-1]; s.lo <= last.hi+1 {
			last.hi = max(last.hi, s.hi)
		} else {
			merged = append(merged, s)
		}
	}

	var out bytes.Buffer

	header, err := os.ReadFile("const.go")
	if err != nil {
		log.Fatal(err)
	}

	end := bytes.Index(header, []byte("*/\n"))
	out.Write(header[:end+3])
	out.WriteString(`
// Code generated by gen_unicode9.go from testdata/ucd/DerivedAge-9.0.0.txt; DO NOT EDIT.

package pathcheck

import "unicode"

// unicode9 holds every code point assigned in Unicode 9.0.
var unicode9 = &unicode.RangeTable{
	R16: []unicode.Range16{
`)

	latin := 0
	for _, s := range merged {
		if s.hi > 0xFFFF {
			continue
		}

		if s.hi <= unicode.MaxLatin1 {
			latin++
		}

		fmt.Fprintf(&out, "\t\t{Lo: 0x%04X, Hi: 0x%04X, Stride: 1},\n", s.lo, s.hi)
	}

	out.WriteString("\t},\n\tR32: []unicode.Range32{\n")

	for _, s := range merged {
		switch {
		case s.lo > 0xFFFF:
			fmt.Fprintf(&out, "\t\t{Lo: 0x%05X, Hi: 0x%05X, Stride: 1},\n", s.lo, s.hi)
		case s.hi > 0xFFFF:
			log.Fatalf("range %X..%X crosses the 16-bit boundary", s.lo, s.hi)
		}
	}

	fmt.Fprintf(&out, "\t},\n\tLatinOffset: %d,\n}\n", latin)

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		log.Fatal(err)
	}

	if err = os.WriteFile("unicode9.go", formatted, 0o600); err != nil {
		log.Fatal(err)
	}
}
